analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  enable-experiment:
    - nonfunction-type-aliases

linter:
  rules:
    avoid_classes_with_only_static_members: false
    avoid_function_literals_in_foreach_calls: false
    constant_identifier_names: false
    file_names: false
    non_constant_identifier_names: false
    prefer_const_constructors: true