name: pj
version: 0.0.1
homepage: https://github.com/cranst0n/pj
description: JSON library built on dartz.

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  dartz:     ^0.10.0
  equatable: ^2.0.3

dev_dependencies:
  faker: ^2.0.0
  test:  ^1.19.3
