name: pj
version: 0.0.5
homepage: https://github.com/cranst0n/pj
description: >
  JSON library built on dartz with the primary aim of making the inherent fallibility explicit.

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  dartz:     ^0.10.1

dev_dependencies:
  coverage:  ^1.0.4
  equatable: ^2.0.3
  faker:     ^2.0.0
  lint:      ^1.0.0
  test:      ^1.17.1
